### ISSUE TITLE
Not getting the latest value when clicking

### ISSUE THREAD

**Issue by Solidus0815** [Polymer/paper-slider#40]
When clicking on the slider instead of dragging the pin the value in the fired event is the last
value instead of the current value.

```
<paper-slider pin snaps min="-10" max="10" step="1" self-stretch
      on-change="{{ valueChanged }}" ></paper-slider>

valueChanged: function (e, detail, sender) {
   console.log(e.target.value);
}
```

To clarify:
click on 5 -> value: 0
click on -3 -> value: 5
click on 0 -> value: -3

Tested on Polymer 0.52,  Chrome 39.0.2171.95

**Comment by frankiefu** [comment]
Seems to be working for me in 0.54
